"""add visible_departments to content

Revision ID: ae27e355c17a
Revises: 28244997e440
Create Date: 2026-06-30 12:49:58.333159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae27e355c17a'
down_revision: Union[str, Sequence[str], None] = '28244997e440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('visible_departments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'visible_departments')
    # ### end Alembic commands ###
