from pydantic import BaseModel, EmailStr
from typing import Optional
from .models import RoleEnum

class UserBase(BaseModel):
    name: str
    email: Optional[EmailStr] = None
    personal_email: EmailStr
    role: RoleEnum
    department: Optional[str] = None
    doj: Optional[str] = None

class UserCreate(UserBase):
    pass # Password is auto-generated by the system

class UserResponse(UserBase):
    id: int
    is_first_login: bool
    is_active: bool

    class Config:
        from_attributes = True

class Token(BaseModel):
    access_token: str
    token_type: str

class TokenData(BaseModel):
    email: Optional[str] = None
    role: Optional[RoleEnum] = None

class PasswordResetConfirm(BaseModel):
    new_password: str

# Content Schemas
class ContentBase(BaseModel):
    title: str
    description: Optional[str] = None
    content_type: str # video, pdf, ppt
    file_url: str
    order: int = 0

class ContentCreate(ContentBase):
    pass

class ContentResponse(ContentBase):
    id: int
    class Config:
        from_attributes = True

# MCQ Schemas
class MCQBase(BaseModel):
    content_id: int
    question: str
    option_a: str
    option_b: str
    option_c: str
    option_d: str
    correct_answer: str # A, B, C, D

class MCQCreate(MCQBase):
    pass

class MCQResponse(MCQBase):
    id: int
    class Config:
        from_attributes = True

# Module Progress Schemas
class ModuleProgressCreate(BaseModel):
    content_id: int
    score: int
    total_questions: int

class ModuleProgressResponse(BaseModel):
    id: int
    user_id: int
    content_id: int
    completed: bool
    score: int
    total_questions: int
    completed_at: Optional[str] = None
    attempt_count: int = 0
    class Config:
        from_attributes = True
