from pydantic import BaseModel, EmailStr
from typing import Optional
from .models import RoleEnum
from typing import List

class UserBase(BaseModel):
    name: str
    email: Optional[EmailStr] = None
    personal_email: EmailStr
    role: RoleEnum
    department: Optional[str] = None
    doj: Optional[str] = None

class UserCreate(UserBase):
    pass # Password is auto-generated by the system

class UserResponse(UserBase):
    id: int
    is_first_login: bool
    is_active: bool

    class Config:
        from_attributes = True

class Token(BaseModel):
    access_token: str
    token_type: str

class TokenData(BaseModel):
    email: Optional[str] = None
    role: Optional[RoleEnum] = None

class PasswordResetConfirm(BaseModel):
    new_password: str

# Content Schemas
class ContentBase(BaseModel):
    title: str
    description: Optional[str] = None
    content_type: str
    file_url: Optional[str] = None
    order: int = 0
    is_intro: bool = False
    is_enabled: bool = True   
    visible_departments: Optional[str] = None 

class ContentCreate(ContentBase):
    pass

class ContentResponse(ContentBase):
    id: int
    is_intro: bool = False
    class Config:
        from_attributes = True

# MCQ Schemas
class MCQBase(BaseModel):
    content_id: int
    question: str
    option_a: str
    option_b: str
    option_c: str
    option_d: str
    correct_answer: str # A, B, C, D

class MCQCreate(MCQBase):
    pass

class MCQResponse(MCQBase):
    id: int
    class Config:
        from_attributes = True

# Module Progress Schemas
class ModuleProgressCreate(BaseModel):
    content_id: int
    score: int
    total_questions: int

class ModuleProgressResponse(BaseModel):
    id: int
    user_id: int
    content_id: int
    completed: bool
    score: int
    total_questions: int
    completed_at: Optional[str] = None
    attempt_count: int = 0
    class Config:
        from_attributes = True

# Employee Submission Schemas
class SubmissionCreate(BaseModel):
    full_name: str
    address: str
    emergency_contact: str

class SubmissionStatusUpdate(BaseModel):
    status: str
    hr_remark: Optional[str] = None

class SubmissionResponse(BaseModel):
    id: int
    user_id: int
    full_name: str
    address: str
    emergency_contact: str
    document_url: Optional[str] = None
    status: str
    hr_remark: Optional[str] = None
    submitted_at: Optional[str] = None
    class Config:
        from_attributes = True

class ReorderRequest(BaseModel):
    content_ids: List[int]

class ModuleReportItem(BaseModel):
    module_title: str
    is_intro: bool
    completed: bool
    score: int
    total_questions: int
    attempt_count: int
    module_score_pct: int
    completed_at: Optional[str] = None
    time_spent_seconds: int = 0

class ReportSummary(BaseModel):
    total_modules: int
    completed_modules: int
    overall_score_pct: int
    rating: str
    acknowledged_at: Optional[str] = None
    completion_date: Optional[str] = None